### Recuperar todas las películas
GET http://localhost:1234/movies
### Recuperar todas las películas por id
GET http://localhost:1234/movies/dcdd0fad-a94c4810-8acc-5f108d3b18c3
### Recuperar todas las películas por género
GET http://localhost:1234/movies?genre=Action